### PR TITLE
Match colour of stock bottom keyguard icons, now following Material Design...

### PR DESCRIPTION
**Pull request by yankarinRG**
Colour is now like the lock icon, since the current fod icon is too white.
- As per [Material Design](https://material.io/design/platform-guidance/android-fingerprint.html#standard-fingerprint) the icon conforms to Material Design guidelines.
- The SVG path was optimized (without reducing quality) and 3a321c6 was improved using fillAlpha.
- VectorDrawable optimized (3 bytes instead of 6 for colour), fillAlpha instead of 2 bytes in fillColor.

Taken from:
- https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-9.0.0_r48/packages/SystemUI/res/layout/keyguard_bottom_area.xml (ic_lock_24dp)
- https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-9.0.0_r48/packages/SystemUI/res/drawable/ic_lock_24dp.xml (wallpaperTextColor)
- https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-9.0.0_r48/packages/SystemUI/res-keyguard/values/styles.xml (primary_text_material_dark)
- https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-9.0.0_r48/core/res/res/color/primary_text_material_dark.xml (disabled_alpha_material_dark & primary_text_default_material_dark)
- https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-9.0.0_r48/core/res/res/values/colors_material.xml

### CODE REVIEW

**Comment by yankarinRG** [comment]
Hello @jhenrique09 , did you get a chance to go to have a look at this PR?

**Comment by jhenrique09** [comment]
This is up to @HlcPereira

**Comment by yankarinRG** [comment]
Thank you for the fast reply, let's wait for him then :)

**Comment by Hlcpereira** [comment]
While on the settings app the Icon isn't visible at it (as it's now white and not the light gray) and also the fingerprint icon inside the circle is smaller. I liked and understood the intention and idea, but I do prefer to keep the FOD icon as it is nowadays. What we can do is maybe use fillAlpha to reduce the feel of the icon being too white?

**Comment by yankarinRG** [comment]
I thought it would be nice to follow Google guidelines (Material Design) as closely as possible since this is Pixel Experience so basically the ROM sold on Pixels ported to non-Pixel devices but, if you like more the current implementation, then let's keep things as they are.
I made a comparison to better visualize this change, and I should admit the proposed version looks very clean!
- [official Material Design recommendation](https://i.imgur.com/itReDPU.png)
- [current keyguard](https://i.imgur.com/FzEfANj.png)
- [proposed keyguard](https://i.imgur.com/mOET7Wi.png)
- [current settings](https://i.imgur.com/2NjltiC.png)
- [proposed settings](https://i.imgur.com/D5QjW8H.png)

.

- The alpha on keyguard is now 0.5 white because the lock icon has 0.5 instead of 0.3 as per the source (strange), so they match colour perfectly.
- The alpha on settings is 0.55 black to match the delete icon colour.

Since we're already in touch, there is a colour bug in the fingerprint settings fragment.
Please take a [look](https://i.imgur.com/a7fdKUA.png): status bar and navigation bar icons are light instead of dark (left: bugged fp fragment, right: stock colours of status bar and navigation bar of similar settings)

**Comment by Hlcpereira** [comment]
What actually is worrying me is not the icon itself, but the fact that here at my Mi 9 SE it kept white on settings. I'm building right now to check if it was another patch that I included to test or anything else.

**Comment by yankarinRG** [comment]
Okay so as I said in my last comment, to perfectly match the lock in keyguard I had to bump alpha from 0.3 to 0.5, so they are now the same exact colour. What we can do when the fingerprint scanner icon is on a light background is we can use, instead of a white (on white) icon, a 55% black on white icon, like [proposed](https://i.imgur.com/D5QjW8H.png). We can achieve in two ways:
- use a separate icon for white backgrounds, like fod_icon_default_dark
- programmatically change the colour of this [VectorDrawable](https://developer.android.com/reference/android/graphics/drawable/VectorDrawable)

This way, there will be the right amount of contrast. Also no problem for the actual scan since when the finger is on the sensor the drawable is removed and is replaced by a bright green tint ;)

P.S. when I say 55% black I mean _fillColor="#000"_ and _fillAlpha="0.55"_ (for the black on white background icon variant).

P.P.S. did you have a look at the [bug](https://i.imgur.com/a7fdKUA.png) I mentioned in the last comment?

**Comment by yankarinRG** [comment]
@Hlcpereira any news mate? :)

**Pull request closed without merging**
